-- Schema bootstrap for the PostgreSQL deployment. Mirrors database/init.sql
-- (SQL Server), which stays the source of truth for the local stack.
-- Idempotent: safe to run on every application start.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    email         VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cars (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    brand        VARCHAR(80) NOT NULL,
    model        VARCHAR(80) NOT NULL,
    year         INT NOT NULL,
    plate_number VARCHAR(20) NOT NULL,
    color        VARCHAR(50) NOT NULL,
    photo_url    VARCHAR(255),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_cars_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- A plate is unique per user (the same plate can't be duplicated by one owner).
CREATE UNIQUE INDEX IF NOT EXISTS uq_cars_user_plate ON cars (user_id, plate_number);
CREATE INDEX IF NOT EXISTS ix_cars_user ON cars (user_id);
